services:
  - type: web
    name: rtts-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false